name: hydroocean-grib
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyside6
  - numpy
  - pandas
  - xarray
  - cfgrib
  - eccodes
  - matplotlib
  - requests
  - pyyaml
  - scipy
  - pillow
  - pyinstaller
  - pytest
